config/routes.rb
# frozen_string_literal: true

##
# @file config/routes.rb
#
# @description Application routes config
#
Rails.application.routes.draw do
  root to: 'home#index'

  # ===========================================================================
  # ActiveRecord Resources
  # ===========================================================================
  resources :articles, :blogs, :projects, :movies, :genres, :sub_genres,
            :regions, :roles, :locations, :people

  # ===========================================================================
  # API
  # ===========================================================================
  namespace :api do
    namespace :v1, defaults: { format: :json } do
      # Articles index
      get '/articles', to: 'articles#index'

      # Articles show
      get '/articles/:slug', to: 'articles#show', as: :article

      # Blogs index
      get '/blogs', to: 'blogs#index'

      # Blogs show
      get '/blogs/:slug', to: 'blogs#show', as: :blog

      # Projects index
      get '/projects', to: 'projects#index'

      # Projects show
      get '/projects/:slug', to: 'projects#show', as: :project

      # Movies index
      get '/movies', to: 'movies#index'

      # Movies show
      get '/movies/:id', to: 'movies#show', as: :movie

      # Search Movie Titles
      post '/movies/search', to: 'movies#search', as: :search_movies

      # Recent Movies
      get '/recent-movies', to: 'recent_movies#index', as: :recent_movies

      # Full Movies Index
      get '/movies-index', to: 'movies_index#index'

      # Movies Index for Bolt Network sliders
      get '/movies-index/:slide_length', to: 'movies_index#show'

      # Genres index
      get '/genres', to: 'genres#index'

      # Genres show
      get '/genres/:slug', to: 'genres#show', as: :genre

      # Search Genres and Movies
      get '/search/:query', to: 'search#show', as: :search
    end
  end

  # ===========================================================================
  # Dashboards
  # ===========================================================================
  get '/api/dashboard', to: 'api/dashboard#index'

  get '/api/data/:model', to: 'api/data#index'

  post '/api/data', to: 'api/data#show'

  # ===========================================================================
  # Query Labs
  # ===========================================================================
  get '/query-labs', to: 'query_labs#show'
end

app/models/project.rb
##
# @file app/models/project.rb
#
# @model Project
#
# @description Model for Projects Table
#
class Project < ApplicationRecord
  # == Extensions ===========================================================

  # == Constants ============================================================

  TECH_OPTIONS = [
    'Ruby on Rails', 'JavaScript', 'HTML5', 'CSS3', 'SASS',
    'NodeJS', 'ReactJS', 'jQuery', 'Bootstrap', 'Heroku'
  ].freeze

  # == Attributes ===========================================================
  # t.string   :title
  # t.string   :slug
  # t.string   :cover
  # t.string   :images, array: true, default: []
  # t.string   :desktop
  # t.string   :mobile, array: true, default: []
  # t.string   :meta_title
  # t.string   :meta_description
  # t.text     :summary
  # t.string   :site_link
  # t.string   :repo_link
  # t.text     :description, array: true, default: []
  # t.string   :features, array: true, default: []
  # t.string   :apis, array: true, default: []
  # t.string   :tech_stack, array: true, default: []

  mount_uploader :cover, PortfolioUploader

  mount_uploaders :images, PortfolioUploader

  mount_uploader :desktop, PortfolioUploader

  mount_uploaders :mobile, PortfolioUploader

  # == Relationships ========================================================

  has_rich_text :content

  # == Validations ==========================================================

  validates :title, :cover, :images, :desktop, :mobile, presence: true

  # == Scopes ===============================================================

  # == Callbacks ============================================================

  # == Class Methods ========================================================

  def self.attributes
    attribute_names.map(&:to_sym)
  end

  def pretty_print
    JSON.pretty_generate(attributes)
  end

  # == Instance Methods =====================================================
end

app/controllers/api/v1/projects_controller.rb
# app/controllers/api/v1/projects_controller.rb

# frozen_string_literal: true

module Api
  module V1
    # API Controller for projects
    class ProjectsController < ApplicationController
      ##
      # GET /api/v1/projects
      #
      def index
        @projects = Project.all
      end

      ##
      # GET /api/v1/projects/:slug
      #
      def show
        @project = Project.find_by(slug: params[:slug])
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit Project.attributes
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <%= render 'resource_errors', resource: project %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :slug %>
    <%= form.text_field :slug, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :cover %>
    <%= form.file_field :cover, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :meta_title, 'Meta Title' %>
    <%= form.text_field :meta_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :meta_description, 'Meta Description' %>
    <%= form.text_area :meta_description, class: 'form-control', size: '24x4' %>
  </div>

  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_area :summary, class: 'form-control', size: '24x4' %>
  </div>

  <div class="form-group">
    <%= form.label :site_link, 'Site Link' %>
    <%= form.url_field :site_link, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :repo_link, 'Repo Link' %>
    <%= form.url_field :repo_link, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', size: '24x4' %>
  </div>

  <div class="form-group">
    <%= form.label :tech_stack, 'Tech Stack' %>
    <%= form.select(
      :tech_stack,
      Project::TECH_OPTIONS,
      { prompt: 'Select Options' },
      {
        class: 'form-control',
        multiple: true,
        size: 8
      }
    ) %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%# app/views/projects/new.html.erb %>

<div class="container pb-5 mb-5">
  <%= render(
    'resource_nav',
    resource: @project,
    index_path: projects_path,
    edit_path: edit_project_path(@project)
  ) %>

  <h1 class="text-center mt-4 mb-4">Edit <%= @project.title %></h1>

  <div class="row justify-content-center">
    <div class="col-12 col-sm-10">
      <%= render 'form', project: @project %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<%# app/views/projects/index.html.erb %>

<p id="notice"><%= notice %></p>

<div class="container">
  <h1 class="text-center mt-4 mb-4">Projects</h1>

  <%= link_to 'New Project', new_project_path, class: 'btn btn-primary mt-4 mb-4' %>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <th scope="row"><%= project.title %></th>

          <td>
            <%=
              link_to 'Show',
                      project,
                      class: 'btn btn-sm btn-outline-info'
            %>
          </td>
          
          <td>
            <%=
              link_to 'Edit',
                      edit_project_path(project),
                      class: 'btn btn-sm btn-outline-success'
            %>
          </td>
          
          <td>
            <%=
              link_to 'Delete',
                      project,
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      class: 'btn btn-sm btn-outline-danger'
            %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/new.html.erb
<%# app/views/projects/new.html.erb %>

<div class="container pb-5 mb-5">
  <h1 class="text-center mt-4 mb-4">New Project</h1>

  <div class="row justify-content-center">
    <div class="col-12 col-sm-10">
      <%= render 'form', project: @project %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<%# app/views/projects/show.html.erb %>

<p id="notice"><%= notice %></p>

<div class="container pb-5">
  <%= render(
    'resource_nav',
    resource: @project,
    index_path: projects_path,
    edit_path: edit_project_path(@project)
  ) %>

  <div class="row justify-content-center mt-4 mb-4">
    <h1><%= @project.title %></h1>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">
          <strong>FIELD</strong>
        </th>
        <th scope="col">
          <strong>VALUE</strong>
        </th>
      </tr>
    </thead>

    <tbody>

    <% @project.attributes.each do |key, value| %>
      <tr>
        <td><%= key.upcase %></td>
        <td><%= value %></td>
      </tr>
    <% end %>

    </tbody>
  </table>
</div>